### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by petar-dambovaliev** [jaredforth/lilypond-rs#1]
Hey, i am making a scripting language for writing and playing music.
I wanted to be able to export lilypond files.
I was looking for Rust bindings and this is the only thing i found.
However, it doesn't seem to provide any functionality yet.

**Comment by jaredforth** [comment]
Hello Petar,

This crate is still very much a work in progress, and does not provide any
real functionality. You can compile a LilyPond file, as described in
https://docs.rs/lilypond/0.1.0/lilypond/fn.compile.html. I have started to
work on creating abstractions over LilyPond concepts in
https://github.com/jaredforth/lilypond-rs/tree/extend, but it has been a
while since I've had time to work on it. Feel free to contribute code, or
create an issue with specific feature requests.

**Comment by sunjay** [comment]
Could you publish a new version of the crate with the latest enhancements that seem to have been made since this issue was created? I'd love to use this! Thanks for taking the time to create it!

**Comment by jaredforth** [comment]
@sunjay Absolute! I just published `v0.1.1`
